#! /bin/bash

DEFAULT_IMAGE_BUILDER_HOSTNAME=lmc-image-builder
DEFAULT_IMAGE_BUILDER_IMAGE=Trusty
DEFAULT_OPENSTACK_SSH_KEY_NAME=sandbox

read -p "Hostname for image builder server ($DEFAULT_IMAGE_BUILDER_HOSTNAME): " IMAGE_BUILDER_HOSTNAME
export IMAGE_BUILDER_HOSTNAME=${IMAGE_BUILDER_HOSTNAME:-$DEFAULT_IMAGE_BUILDER_HOSTNAME}

read -p "Image to use to create image builder server ($DEFAULT_IMAGE_BUILDER_IMAGE): " IMAGE_BUILDER_IMAGE
export IMAGE_BUILDER_IMAGE=${IMAGE_BUILDER_IMAGE:-$DEFAULT_IMAGE_BUILDER_IMAGE}

read -p "OpenStack SSH key name ($DEFAULT_OPENSTACK_SSH_KEY_NAME): " OPENSTACK_SSH_KEY_NAME
export OPENSTACK_SSH_KEY_NAME=${OPENSTACK_SSH_KEY_NAME:-$DEFAULT_OPENSTACK_SSH_KEY_NAME}

DEFAULT_OPENSTACK_SSH_KEY_PATH=~/Credentials/yeg/$OPENSTACK_SSH_KEY_NAME/$OPENSTACK_SSH_KEY_NAME.pem

read -p "OpenStack SSH key path ($DEFAULT_OPENSTACK_SSH_KEY_PATH): " OPENSTACK_SSH_KEY_PATH
export OPENSTACK_SSH_KEY_PATH=${OPENSTACK_SSH_KEY_PATH:-$DEFAULT_OPENSTACK_SSH_KEY_PATH}

cd vagrant
vagrant up --provider=openstack
