#vagrant plugin install vagrant-openstack-plugin
#vagrant box add dummy https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box

require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  ssh_key = ENV['OPENSTACK_SSH_KEY_PATH'] || "images.pem"
  keypair = ENV['OPENSTACK_SSH_KEY_NAME'] || "images"
  image = ENV['IMAGE_BUILDER_IMAGE'] || "Ubuntu 14.04"

  config.ssh.private_key_path = ssh_key

  # Basic OpenStack options
  # Note that an openrc file needs sourced before using
  config.vm.provider :openstack do |os|
    os.username         = ENV['OS_USERNAME']
    os.api_key          = ENV['OS_PASSWORD']
    os.tenant           = ENV['OS_TENANT_NAME']
    os.region           = ENV['OS_REGION_NAME']
    os.flavor           = /m1.small/
    os.image            = image
    os.endpoint         = "#{ENV['OS_AUTH_URL']}/tokens"
    os.keypair_name     = keypair
    os.networks         = []
    os.floating_ip      = :auto
    os.floating_ip_pool = 'nova'
    os.ssh_username     = "ubuntu"
    os.security_groups  = ['default']
    os.address_id       = 'cybera'
  end

  config.vm.define (ENV['IMAGE_BUILDER_HOSTNAME'] || "packer.example.com") do |vm|
    vm.vm.provision 'shell', path: 'bootstrap.sh'
  end

end
